### ISSUE TITLE
Fails to deploy due to dependencies missing, and layer-options appear to be missing

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/layer-docker#33] opened 2016-04-04 18:05 UTC
Hi Chuck, 
Trying to run a docker layered charm this morning on GCE, it seems there is an issue with the vcversioner. See trace below, this is Juju 1.25 on 15.10, deploying Trusty. 

```
unit-deepdetect-0[13577]: 2016-04-04 18:00:45 INFO unit.deepdetect/0.install logger.go:40 Processing ./wheelhouse/Jinja2-2.8.tar.gz
unit-deepdetect-0[13577]: 2016-04-04 18:00:45 INFO unit.deepdetect/0.install logger.go:40 Processing ./wheelhouse/docker-py-1.7.2.tar.gz
unit-deepdetect-0[13577]: 2016-04-04 18:00:45 INFO unit.deepdetect/0.install logger.go:40 Processing ./wheelhouse/requests-2.7.0.tar.gz
unit-deepdetect-0[13577]: 2016-04-04 18:00:46 INFO unit.deepdetect/0.install logger.go:40 Processing ./wheelhouse/websocket_client-0.35.0.tar.gz
unit-deepdetect-0[13577]: 2016-04-04 18:00:46 INFO unit.deepdetect/0.install logger.go:40 Processing ./wheelhouse/pyaml-15.8.2.tar.gz
unit-deepdetect-0[13577]: 2016-04-04 18:00:46 INFO unit.deepdetect/0.install logger.go:40 Processing ./wheelhouse/texttable-0.8.4.tar.gz
unit-deepdetect-0[13577]: 2016-04-04 18:00:46 INFO unit.deepdetect/0.install logger.go:40 Processing ./wheelhouse/docopt-0.6.2.tar.gz
unit-deepdetect-0[13577]: 2016-04-04 18:00:46 INFO unit.deepdetect/0.install logger.go:40 Processing ./wheelhouse/jsonschema-2.5.1.tar.gz
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     Complete output from command python setup.py egg_info:
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     Note: Bypassing https://pypi.python.org/simple/vcversioner/ (disallowed host; see http://bit.ly/1dg9ijs for details).
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     Couldn't find index page for 'vcversioner' (maybe misspelled?)
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     Note: Bypassing https://pypi.python.org/simple/ (disallowed host; see http://bit.ly/1dg9ijs for details).
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     No local packages or download links found for vcversioner
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     Traceback (most recent call last):
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40       File "<string>", line 20, in <module>
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40       File "/tmp/pip-m1i7shz7-build/setup.py", line 44, in <module>
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40         vcversioner={"version_module_paths" : ["jsonschema/_version.py"]},
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40       File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40         _setup_distribution = dist = klass(attrs)
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 239, in __init__
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40         self.fetch_build_eggs(attrs.pop('setup_requires'))
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40         replace_conflicting=True
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40       File "/usr/lib/python3/dist-packages/pkg_resources.py", line 620, in resolve
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40         dist = best[req.key] = env.best_match(req, ws, installer)
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40       File "/usr/lib/python3/dist-packages/pkg_resources.py", line 858, in best_match
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40         return self.obtain(req, installer) # try and download/install
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40       File "/usr/lib/python3/dist-packages/pkg_resources.py", line 870, in obtain
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40         return installer(requirement)
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40       File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40         return cmd.easy_install(req)
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40       File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 610, in easy_install
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40         raise DistutilsError(msg)
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('vcversioner')
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     ----------------------------------------
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-m1i7shz7-build
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40 Traceback (most recent call last):
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40   File "/var/lib/juju/agents/unit-deepdetect-0/charm/hooks/install", line 8, in <module>
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     basic.bootstrap_charm_deps()
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40   File "lib/charms/layer/basic.py", line 70, in bootstrap_charm_deps
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     glob('wheelhouse/*'))
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40     raise CalledProcessError(retcode, cmd)
unit-deepdetect-0[13577]: 2016-04-04 18:00:47 INFO unit.deepdetect/0.install logger.go:40 subprocess.CalledProcessError: Command '['pip3', 'install', '-U', '--no-index', '-f', 'wheelhouse', 'wheelhouse/Jinja2-2.8.tar.gz', 'wheelhouse/docker-py-1.7.2.tar.gz', 'wheelhouse/requests-2.7.0.tar.gz', 'wheelhouse/websocket_client-0.35.0.tar.gz', 'wheelhouse/pyaml-15.8.2.tar.gz', 'wheelhouse/texttable-0.8.4.tar.gz', 'wheelhouse/docopt-0.6.2.tar.gz', 'wheelhouse/jsonschema-2.5.1.tar.gz', 'wheelhouse/pip-7.1.2.tar.gz', 'wheelhouse/netaddr-0.7.18.tar.gz', 'wheelhouse/PyYAML-3.11.tar.gz', 'wheelhouse/dockerpty-0.4.1.tar.gz', 'wheelhouse/six-1.10.0.tar.gz', 'wheelhouse/cached-property-1.3.0.tar.gz', 'wheelhouse/charmhelpers-0.7.0.tar.gz', 'wheelhouse/charms.reactive-0.4.0.tar.gz', 'wheelhouse/docker-compose-1.6.2.tar.gz', 'wheelhouse/charms.docker-0.1.2.tar.gz', 'wheelhouse/MarkupSafe-0.23.tar.gz', 'wheelhouse/Tempita-0.5.2.tar.gz']' returned non-zero exit status 1
```

**Comment by SaMnCo** [comment] 2016-04-04 18:13
To fix, I did ssh into the machine, then ```sudo pip3 install vcversioner```

But then I get into the error we discussed the other day with Emmanuel

```
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.juju-log server.go:268 Reactive main running for hook install
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.juju-log server.go:268 Invoking reactive handler: reactive/docker.py:29:install
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40 Traceback (most recent call last):
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40   File "/var/lib/juju/agents/unit-deepdetect-0/charm/hooks/install", line 19, in <module>
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40     main()
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/__init__.py", line 69, in main
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40     bus.dispatch()
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 410, in dispatch
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40     _invoke(hook_handlers)
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 401, in _invoke
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40     handler.invoke()
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40   File "/usr/local/lib/python3.4/dist-packages/charms/reactive/bus.py", line 277, in invoke
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40     self._action(*args)
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40   File "/var/lib/juju/agents/unit-deepdetect-0/charm/reactive/docker.py", line 38, in install
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40     if layer_opts['skip-install']:
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 INFO unit.deepdetect/0.install logger.go:40 KeyError: 'skip-install'
unit-deepdetect-0[13577]: 2016-04-04 18:07:19 ERROR juju.worker.uniter.operation runhook.go:107 hook "install" failed: exit status 1
```

Thoughts?

**Comment by SaMnCo** [comment] 2016-04-04 18:18
Which then if I comment the section about "skip-install" in the docker.py file, allows me to move forward. 

So the sequence of errors is: 
1. vcversioner to be installed separately prior to the rest (I have found refs about this all over the web, strange we have it only now)
2. Fix the docker.py to handle the skip-install better

Thanks :)

**Comment by chuckbutler** [comment] 2016-04-07 17:28
Greetings Sam,

Thanks for reporting this bug! Its actually more widespread than just GCE. I've confirmed this affects all providers and is actually a combination of things.

1) You've identified that vcversioner is an issue, and due to that i've added it ot the wheelhouse to ensure we're bundling/shipping the dependency with the charm.
2) The skip-install option breakage is due to the version of charm-tools you have installed. The most recent editions of `layer-docker` have been tracking tip of charm-tools pretty heavilly to leverage the new features. Charm-tools didn't grow support for layer-options until: 1.11.1

You can get this version using the PPA's (both juju-stable and juju-devel)

if you're on OSX/Windows the process is not as straight forward, and I would suggest you take a look at [charmbox:devel](https://github.com/juju-solutions/charmbox/tree/devel) to get the latest and greatest in a hermetically sealed runtime environment.

I apologize for the inconvenience, and will ensure we get the fixes in + documentation updates to outline the requirements for building from layer-docker as we continue to push the envelope.

**Comment by chuckbutler** [comment] 2016-04-11 17:20
This needs a documentation update in the README outlining the minimum version of charm-tools before the issue is resolved with any level of satisfaction.

**Comment by chuckbutler** [comment] 2016-07-05 19:22
I think this issue is sufficiently aged to close, as charm-tools has had a few releases since this and is now in archive in Xenial.

**Closed by chuckbutler** 2016-07-05 19:22 UTC
Labels: bug, Priority: medium, Triaged

**Comment by hamsterksu** [comment] 2016-11-07 15:24
hi everybody, i have got this error on juju 2.0.1 and charm-tools 2.1.5

**Comment by chuckbutler** [comment] 2016-11-07 15:52
@hamsterksu Is this issue only with charms using layer-docker, or are you receiving a traceback regarding pip packages on all assembled charms?

**Comment by hamsterksu** [comment] 2016-11-07 15:54
@chuckbutler i got this error with layer-docker. it's my simple charm - https://github.com/dataart-telco/restcomm-charm

**Comment by hamsterksu** [comment] 2016-11-07 16:07
@chuckbutler seems it was fault, i uses `composer.yaml` file instead of `layer.yaml`
i have renamed it and was added options for docker there. so it works now.
sorry for troubling

**Comment by chuckbutler** [comment] 2016-11-07 16:31
Ok Great :)
