### ISSUE TITLE
Race time condition when deploying new k8s clusters with insecure registries

### ISSUE THREAD

**Issue by CalvinHartwell** [juju-solutions/layer-docker#112] opened 2018-01-31 16:54 UTC
Hi all,

We believe we have found a race condition when deploying new Kubernetes clusters using both the docker-logins and docker-opts parameters. 

During a new cluster built if both of these parameters are set when the cluster is deployed, we believe the docker-logins parameter is set, but not the docker-opts parameter, which causes an error. Basically kubernetes can't log into the private registry it just configured for itself because it doesn't trust the SSL certificates for these registries or they are only using HTTP and not HTTPS. 

```
docker-logins:
    default: '[]'
    description: |
      Docker login credentials. Setting this config allows Kubelet to pull images from
      registries where auth is required.

      The value for this config must be a JSON array of credential objects, like this:
        [{"server": "my.registry", "username": "myUser", "password": "myPass"}]
    source: user
    type: string
    value: '[{"server": "192.168.197.30:5555", "username": "kubernetes_deploy", "password":
      "KubeNexus01"}]'
  docker-opts:
    default: ""
    description: |
      Extra options to pass to the docker daemon. e.g. --insecure-registry
    source: user
    type: string
    value: --insecure-registry 192.168.197.30:5555
```

We have tested setting these options after the cluster is deployed and that works fine. The values we are specifying for these parameters are correct also. 

Cheers,

- Calvin

**Comment by jeff-hillman** [comment] 2018-02-01 11:40
To further clarify, if the docker-logins parameter is set inside of the kubernetes-worker BEFORE the docker-opts is set specifying the insecure registry, then the kubernetes-worker unit will fail and discontinue deploying.

We must manually edit /etc/default/docker and add the insecure registry option, then restart docker and finally run juju resolved against the unit for the deploy to continue.

**Comment by kwmonroe** [comment] 2018-02-02 07:43
`docker_template_update()` from [layer-docker](https://github.com/juju-solutions/layer-docker/blob/master/reactive/docker.py) handles changes to the `docker-opts` config, while `docker_logins_changed()` in [k8s-worker](https://github.com/kubernetes/kubernetes/blob/master/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py) handles `docker-logins` changes.  The issue is that we can't be sure of the order that these config functions will be executed.

A simple fix may be to adjust `docker_logins_changed()` in `./reactive/kubernetes-worker.py` so we always check for new docker opts (and restart the daemon if needed) before doing any `docker log[out|in]`.  Something like this:

```diff
@@ -451,8 +451,16 @@ def extra_args_changed():


 @when('config.changed.docker-logins')
+@when_not('docker.restart')
 def docker_logins_changed():
     config = hookenv.config()
+
+    # See if we need to restart the docker daemon before logout/login
+    if data_changed('docker-opts', config['docker-opts']):
+        # State is removed in layer-docker after restart
+        set_state('docker.restart')
+        return
+
     previous_logins = config.previous('docker-logins')
     logins = config['docker-logins']
     logins = json.loads(logins)
```

I need to test this, but I should have something packaged and pushed to the store for you guys to try tomorrow.

One concern I have is that `data_changed` may be true on the first run, so we may be recycling the docker daemon (once) for no reason. I haven't come up with any other concerns for enforcing a restart in the logins handler upon opts changes.  Feedback/concerns are most welcome!

**Comment by jeff-hillman** [comment] 2018-02-02 09:23
I don't see a concern there.  I would expect charm config changes would either happen during deploy/test or maintenance.  Therefore, nothing would be being pulled from repos that a refresh of the credentials would affect.

**Comment by CalvinHartwell** [comment] 2018-02-02 10:29
@kwmonroe very good news, thanks for looking at this so quickly. 

> I need to test this, but I should have something packaged and pushed to the store for you guys to try tomorrow.

We will be on-site again next week, so we can continue testing here as well.

**Comment by kwmonroe** [comment] 2018-02-05 05:59
Hey @CalvinHartwell @jeff-hillman, rev 95 of k8s-worker has this change for you to test:

https://jujucharms.com/u/containers/kubernetes-worker/95

This still needs to be proposed/merged upstream before making its way to the stable channel, but it has passed initial tests on my end.  Let me know if -95 solves this issue for you.

**Comment by kwmonroe** [comment] 2018-05-16 18:58
Oof, this has been fixed upstream for a while now.. k8s-worker charms > rev 100(ish) should contain this fix.

**Closed by kwmonroe** 2018-05-16 18:58 UTC
Labels: Priority: high, bug
